### ISSUE TITLE
List of tagged objects

### ISSUE THREAD

**Issue by michalkleiner** [chrometoasters/silverstripe-advanced-taxonomies#1]
As a CMS user,
I want to be able to see a list of objects a taxonomy term was assigned to
so that I have an overview of the term's use and an easy way to navigate directly to the tagged objects.

The list should be customisable via extension hooks and list all possible relations to the term, i.e. has_one, has_many and many_many (standard and via the 'through' mechanism) relations.

**Comment by normann** [comment]
PR #4 added

**Comment by normann** [comment]
@michalkleiner give the PR ⬆️ a review, please? Cheers.

**Comment by michalkleiner** [comment]
Resolved via #4, thanks @normann
